# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  vvjappwithdatadog:
    image: vvjappwithdatadog
    build:
      context: .
      dockerfile: src/webapi/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CERT_PASSWORD_DEV
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - DD_TRACE_AGENT_URL:http://ddagent:8126
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
  ddagent:
    image: datadog/agent
    environment: 
      - DD_API_KEY=$DD_API_KEY_DEV
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
